### PR TITLE
[Fix] set `Symbol.toStringTag` when available

### LINKED ISSUE #396: Object.prototype.toString.call(form) returns "[object Object]" instead of "[object FormData]"
This appears to be due to a change in the algorithm used for determining the toString of an Object. See step 16 of [19.1.3.6 Object.prototype.toString ( )](https://www.ecma-international.org/ecma-262/6.0/#sec-object.prototype.tostring)

```js
const form = new FormData();

assert(form.toString() == "[object FormData]", "toString() results in [object FormData]")
assert(Object.prototype.toString.call(form) == "[object FormData]", "Object.prototype.toString.call(form) results in [object FormData]")
```

In version 2.3.2 of FormData, the second assertion will fail as `Object.prototype.toString.call(form)` returns `[object Object]`

The fix for this is to add support for the toStringTag symbol, like the following:

```js
if (Symbol && Symbol.toStringTag) {
  Object.defineProperty(FormData.prototype, Symbol.toStringTag, {
    value: 'FormData',
    writable: false,
    enumerable: false,
    configurable: true
  });
}
```

### PR DESCRIPTION
**Pull request by ExE-Boss**
Fixes #396

### CODE REVIEW

File: lib/form_data.js [hunk 1]
```diff
@@ -496,6 +497,16 @@ FormData.prototype._error = function(err) {
...
+    __proto__: null,
+    configurable: true,
+    enumerable: false,
+    writable: false,
+    value: 'FormData',
+  });
+} else {
+  FormData.prototype.toString = function () {
+    return '[object FormData]';
+  };
```
Comment (ljharb) [inline lib/form_data.js:511]: the toString is not the same as toStringTag, and shouldn't be defined at all - separately, i have a package for this already, es-set-tostringtag

**Review by ljharb — CHANGES_REQUESTED** [review]

**Review by ljharb — APPROVED** [review]
